Add bookings
Bolohonov/java-shareit pull request #3
Opened 2022-07-19 09:50 UTC by Bolohonov

Реализовано ТЗ 14 спринта

2022-07-20 07:41 UTC, kukolev requested changes

2022-07-20 07:41 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                .orElseThrow(() -> {
Выброс исключения это часть логики приложения. Логику нужно делать в сервисах.

2022-07-20 07:41 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/repository/InMemoryItemRepositoryTest.java
> +//package ru.practicum.shareit.item.repository;
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-07-20 07:41 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +            "where (upper(i.name) like upper(concat('%', ?2, '%')) " +
Логику поиска LIKE %...% нужно применять только там, где это точно нужно. Дело в том, что при таком запросе будет происходить неиндексированный поиск. Это будет работать медленно при большом количестве данных.

2022-07-20 07:41 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                                LocalDate.now(ZoneId.of("GMT+03:00")),
Зону лучше вынести в константы, чтобы не дублировать везде одинаковый код. Также так шанс ошибиться будет меньше.

2022-07-20 07:41 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                        .stream()
Этот код отличается от аналогичного блока выше только статусом - WAITING и REJECTED. Код можно обобщить и вынести в приватный метод. Так будет меньше кода и это будет лучше читаться. 

Аналогично нужно поправить в остальных подобных местах.

2022-07-21 07:32 UTC, kukolev requested changes

2022-07-21 07:32 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    Collection<Item> searchItemsByNameContainingIgnoreCaseOrDescriptionContainingIgnoreCase(String text, String same);
По моему лучше не делать такие длинные конструкции на Spring Data, а добавить аннотацию @Query c запросом. Название метода при этом можно сделать так, чтобы отражало назначение метода. Так код будет понятней.

P.S. Раньше было лучше, просто логика поиска вызывает сомнение. Если логика поиска такая, какая нужна, то ее можно оставить. Но вот такие длинные предложения в названии методов читать тяжело.

2022-07-21 07:32 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private static final LocalDateTime NOW = LocalDateTime.now(ZoneId.of("GMT+03:00"));
Такая константа приведет к ошибке в работе программы. Дело в том, что значение даты теперь вычисляется в момент старта программы, а не в момент выполнения кода, в котором 
эта константа применяется. Наше приложение серверное и может работать в режиме 24/7. Таким образом значение константы может быть далеко в прошлом в момент выполнения кода.

2022-07-21 11:31 UTC, Bolohonov commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +            "where (upper(i.name) like upper(concat('%', ?2, '%')) " +
Т.е. использовать вместо LIKE индексированный поиск  - запросы с @@ и to_tsvector() (других вариантов с нативными SQL запросами я не нашел для Postgres). Но тестовая база h2 , но там иначе подключается индексированный поиск. Может быть оставим пока так ?

2022-07-21 12:45 UTC, Bolohonov commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    Collection<Item> searchItemsByNameContainingIgnoreCaseOrDescriptionContainingIgnoreCase(String text, String same);
Т.е. использовать вместо LIKE индексированный поиск - запросы с @@ и to_tsvector() (других вариантов с нативными SQL запросами я не нашел для Postgres). Но тестовая база h2 , но там иначе подключается индексированный поиск. Может быть оставим пока так ?

2022-07-21 17:29 UTC, kukolev approved these changes

2022-07-22 06:12 UTC, merged